CREATE DATABASE ecommerce_sales;

USE ecommerce_sales;
SELECT COUNT(*) FROM superstore;


-- QUERY 1 : Total Records
-- Business Question: How many records are present in the dataset?

SELECT COUNT(*) AS Total_Records
FROM superstore;



-- QUERY 2 : Display First 10 Records
-- Business Question: What does the dataset look like?
SELECT *
FROM superstore
LIMIT 10;


-- QUERY 3 : Total Sales
-- Business Question: What is the total sales generated by the company?

SELECT ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore;



-- QUERY 4 : Total Profit
-- Business Question: What is the total profit earned by the company?


SELECT ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore;

-- QUERY 5 : Average Sales
-- Business Question: What is the average sales value per transaction?


SELECT ROUND(AVG(Sales),2) AS Average_Sales
FROM superstore;


-- QUERY 6 : Highest Sales
-- Business Question: What is the highest sales amount recorded?

SELECT MAX(Sales) AS Highest_Sales
FROM superstore;

-- QUERY 7 : Lowest Sales
-- Business Question:
-- What is the lowest sales amount recorded?

SELECT MIN(Sales) AS Lowest_Sales
FROM superstore;


-- QUERY 8 : Total Orders
-- Business Question: How many unique orders are present?


SELECT COUNT(DISTINCT `Order ID`) AS Total_Orders
FROM superstore;

-- QUERY 9 : Sales by Category
-- Business Question:
-- Which product category generates the highest sales?

SELECT Category,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;


-- QUERY 10 : Profit by Category

SELECT Category,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY Category
ORDER BY Total_Profit DESC;


-- QUERY 11 : Sales by Region

SELECT Region,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;



-- QUERY 12 : Sales by Segment

SELECT Segment,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY Segment
ORDER BY Total_Sales DESC;


-- QUERY 13 : Profit by Region

SELECT Region,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY Region
ORDER BY Total_Profit DESC;



-- QUERY 14 : Orders by Ship Mode

SELECT `Ship Mode`,
       COUNT(*) AS Total_Orders
FROM superstore
GROUP BY `Ship Mode`
ORDER BY Total_Orders DESC;


-- QUERY 15 : Top 10 Customers

SELECT `Customer Name`,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY `Customer Name`
ORDER BY Total_Sales DESC
LIMIT 10;


-- QUERY 16 : Top 10 Products

SELECT `Product Name`,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY `Product Name`
ORDER BY Total_Sales DESC
LIMIT 10;



-- QUERY 17 : Sales by State

SELECT State,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY State
ORDER BY Total_Sales DESC;



-- QUERY 18 : Profit by State

SELECT State,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY State
ORDER BY Total_Profit DESC;

-- Query 19 : Sales Greater Than $1000
-- Business Question: Which orders have sales greater than $1000?

SELECT *
FROM superstore
WHERE Sales > 1000;

-- Query 20 : Loss Making Orders
-- Business Question: Which orders resulted in a loss?

SELECT *
FROM superstore
WHERE Profit < 0;

-- Query 21 : Technology Products
-- Business Question: Show all products belonging to the Technology category.

SELECT *
FROM superstore
WHERE Category = 'Technology';

-- Query 22 : Sales Between $500 and $1000
-- Business Question: Which orders have sales between $500 and $1000?

SELECT *
FROM superstore
WHERE Sales BETWEEN 500 AND 1000;

-- Query 23 : Customers from California
-- Business Question: Which customers belong to California?

SELECT `Customer Name`,
       State,
       Sales
FROM superstore
WHERE State = 'California';

-- Query 24 : Categories with Sales Greater Than $700,000
-- Business Question: Which categories generated sales greater than $700,000?

SELECT Category,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY Category
HAVING SUM(Sales) > 700000;

-- Query 25 : Profit Status
-- Business Question: Classify each order as Profit or Loss.

SELECT `Order ID`,
       Profit,
       CASE
           WHEN Profit > 0 THEN 'Profit'
           ELSE 'Loss'
       END AS Profit_Status
FROM superstore;

-- Query 26 : Orders in 2017
-- Business Question: Show all orders placed in 2017.

SELECT *
FROM superstore
WHERE YEAR(`Order Date`) = 2017;

-- Query 27 : Monthly Sales
-- Business Question: What are the monthly sales trends?

SELECT MONTHNAME(`Order Date`) AS Month,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM superstore
GROUP BY MONTH(`Order Date`), MONTHNAME(`Order Date`)
ORDER BY MONTH(`Order Date`);

-- Query 28 : Top 5 Most Profitable Products
-- Business Question: Which are the top 5 most profitable products?

SELECT `Product Name`,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY `Product Name`
ORDER BY Total_Profit DESC
LIMIT 5;

-- Query 29 : Top 5 States by Profit
-- Business Question: Which states generate the highest profit?

SELECT State,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM superstore
GROUP BY State
ORDER BY Total_Profit DESC
LIMIT 5;

-- Query 30 : Average Discount by Category
-- Business Question: What is the average discount offered in each category?

SELECT Category,
       ROUND(AVG(Discount),2) AS Average_Discount
FROM superstore
GROUP BY Category;

-- Query 31 : Rank Products by Sales
-- Business Question: Rank products based on total sales.

SELECT `Product Name`,
       ROUND(SUM(Sales),2) AS Total_Sales,
       RANK() OVER(ORDER BY SUM(Sales) DESC) AS Sales_Rank
FROM superstore
GROUP BY `Product Name`;

-- Query 32 : Top Customer in Each Region
-- Business Question: Who is the highest-selling customer in each region?

WITH CustomerSales AS (
    SELECT Region,
           `Customer Name`,
           ROUND(SUM(Sales),2) AS Total_Sales,
           RANK() OVER(PARTITION BY Region ORDER BY SUM(Sales) DESC) AS Rank_No
    FROM superstore
    GROUP BY Region, `Customer Name`
)

SELECT *
FROM CustomerSales
WHERE Rank_No = 1;

-- Query 33 : Sales Category
-- Business Question: Categorize orders based on sales amount.

SELECT `Order ID`,
       Sales,
       CASE
           WHEN Sales >= 1000 THEN 'High Sales'
           WHEN Sales >= 500 THEN 'Medium Sales'
           ELSE 'Low Sales'
       END AS Sales_Category
FROM superstore;


